### ISSUE TITLE
Many problems not solver with 4.4.4

### ISSUE THREAD

**Issue by SalahAdDin** [riklaunim/django-ckeditor#54] opened 2014-09-13 18:20 UTC
Hi men, i updated your package, and i see that now we can config better this apps, but, we have the next problems.

First, my settings config are this:

``` python
CKEDITOR_CONFIGS = {
    'default': {
        #'skin': 'office2013',
        'toolbar': [
            { 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ], 'items': [ 'Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates' ] },
            { 'name': 'clipboard', 'groups': [ 'clipboard', 'undo' ], 'items': [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
            { 'name': 'editing', 'groups': [ 'find', 'selection', 'spellchecker' ], 'items': [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
            { 'name': 'forms', 'items': [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ] },
            '/',
            { 'name': 'basicstyles', 'groups': [ 'basicstyles', 'cleanup' ], 'items': [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
            { 'name': 'paragraph', 'groups': [ 'list', 'indent', 'blocks', 'align', 'bidi' ], 'items': [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
            { 'name': 'links', 'items': [ 'Link', 'Unlink', 'Anchor' ] },
            { 'name': 'insert', 'items': [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
            '/',
            { 'name': 'styles', 'items': [ 'Styles', 'Format', 'Font', 'FontSize' ] },
            { 'name': 'colors', 'items': [ 'TextColor', 'BGColor' ] },
            { 'name': 'tools', 'items': [ 'Maximize', 'ShowBlocks' ] },
            { 'name': 'others', 'items': [ '-' ] },
            { 'name': 'about', 'items': [ 'About' ] }
        ],
        'width': 650,
        'language': 'es',
        'toolbarCanCollapse' : 'true',
        'toolbarGropus':[
            { 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] },
            { 'name': 'clipboard', 'groups': [ 'clipboard', 'undo' ] },
            { 'name': 'editing', 'groups': [ 'find', 'selection', 'spellchecker' ] },
            { 'name': 'forms' },
            '/',
            { 'name': 'basicstyles', 'groups': [ 'basicstyles', 'cleanup' ] },
            { 'name': 'paragraph', 'groups': [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
            { 'name': 'links' },
            { 'name': 'insert' },
            '/',
            { 'name': 'styles' },
            { 'name': 'colors' },
            { 'name': 'tools' },
            { 'name': 'others' },
            { 'name': 'about' }
        ],
    },
}
```

As you can see, firts, isn't possible user other skins, if i cut the #, ckeditor can't see by us, very bad.

Then, 'toolbarGropus' can't be config. Yes, is i cut the toolbar config, we can't see anything, don't works. Only works toolbarconfig. 

And, in the last, many toolbar icons don't appear in the toolbar, see!
![problemas con ckeditr](https://cloud.githubusercontent.com/assets/5034215/4261503/62853e96-3b72-11e4-9f60-1a86ba3128a9.png)

Is very good can now using most completly toolbar, but, without icons, don't works for the people.

Oh, yes, as can you see, now, ckeditor form aren't allign with other field, he have a offside, and, this is very bad in django-suit.

Thank you!

**Comment by riklaunim** [comment] 2014-09-13 18:22
check if the images that return 404 are in the package or if they are external ckeditor plugins not provided with ckeditor itself.

Left padding may have been caused by inline editor fix. That probably would have to be optional. I do not test it with grappeli.

**Comment by SalahAdDin** [comment] 2014-09-13 18:33
Well, i'm using Django-Suit, not grappeli. 
Before of the update, don't have this padding, now, i have.

See, with office2013 Skin don't have problem with the icons, but, with monoo i have proble.
![skinsoffice2013](https://cloud.githubusercontent.com/assets/5034215/4261556/725b222a-3b74-11e4-880c-4aab243d5570.png)

Is beautiful with this skin.

**Comment by riklaunim** [comment] 2014-09-13 18:35
Try overriding ckeditor/widget.html template (source: https://github.com/riklaunim/django-ckeditor/blob/master/ckeditor/templates/ckeditor/widget.html ) and copy the code except the margin-left style.

**Comment by SalahAdDin** [comment] 2014-09-13 18:38
And i don't know is the languages config works:

``` python
languages : {
        'ar' : 1,
        'en' : 1,
        'es' : 1,
        'ru' : 1,
        'tr' : 1
    }
```

is you want i can to do a pull request with Office2013 skin and margin-left fix.

Yes, margin-left should be auto.

**Comment by riklaunim** [comment] 2014-09-13 18:44
any extras should be managed by users. Adding more and more pluings to the core package is not a good idea. Margin problem will be solved.

**Comment by SalahAdDin** [comment] 2014-09-13 19:59
But, in server, could be difficult to put other plugins or skins.
I think that you should put the full monoo skin, I think that this is probably the issue with icons.

**Comment by riklaunim** [comment] 2014-09-13 20:12
it would not be difficult to put static files and some JS configuration in you project. The point of plugins is that they are optional, additional.

**Comment by SalahAdDin** [comment] 2014-09-13 20:29
The skinks are a folder, no js files.

**Comment by riklaunim** [comment] 2014-09-13 20:46
So whats the problem?

**Comment by SalahAdDin** [comment] 2014-09-13 20:51
In the server isn't easy put other folders. It's more easily use collecstatic with folder skin into the package.

**Comment by riklaunim** [comment] 2014-09-13 21:46
I don't see any problems - on development you have staticfiles finders and on production collectstatic. That ought to allow you to put any plugins you want. If needed you may also fork this application and add needed plugins, package it and use in you projects.

**Comment by SalahAdDin** [comment] 2014-09-13 22:20
Or maybe, i think, create a tree folder structure, same with your folder project and put then the skin folder, then, theory... When I do collecstatic, alll giles will be in the same folder.
Well, I think, jajajajajajsj I'm crazy

**Comment by SalahAdDin** [comment] 2014-09-16 01:26
Now, don't works the office skin and the monoo skin works perfectly!

**Comment by riklaunim** [comment] 2014-09-22 23:53
django-ckeditor 4.4.6 released with some fixes. Should be much better.

**Closed as completed by riklaunim** 2014-09-22 23:53 UTC
